import {getArticles} from '../utils/contentful-helper'
import {formatPublishedDateForDateTime, formatPublishedDateForDisplay,} from '../utils/date'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export const getStaticProps = async () => {

  const data = await getArticles();
  //console.log('postCollection = ', data.postCollection)

  return{
    props: { articles: data.postCollection.items }
  }
}

export default function Home(articles) {

  //console.log('articles = ', articles); //data.postCollection.items.articles
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to HC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} style={{paddingTop:500 + 'px'}}>
        <h1 className={styles.title}>
          Articles
        </h1>

        <div className={styles.grid}>   
    
         {/*articles.articles.map( (article) => <Link 
              key = {article.sys.id}
              className = {styles.card}
              href = {`/article/${article.stackbitUrlPath}`}
            >
            <div>
              <span>{/*formatPublishedDateForDateTime(article.date)* /}</span>
              <h3>{article.title}</h3>
              <p>{article.subtitle}</p>
            </div>
          </Link> 
         )*/} 


      <div className="post-feed" style={{paddingTop:100 + 'px'}}>
      {articles.articles.map( (article) => <Link 
                    key = {article.sys.id}
                    className = {styles.card}
                    href = {`/article/${article.stackbitUrlPath}`}
                  >
        <article className="post post-card">
          <div className="post-card-inside">
            <a class="post-card-thumbnail" href={`/article/${article.stackbitUrlPath}`}>
              <img class="thumbnail" src={article.thumbImgPath.url} alt={article.title} width="500" height="200"/>
            </a>
            <div className="post-card-content">
              <header className="post-header">
                <div className="post-meta">
                  <time className="published" dateTime={formatPublishedDateForDateTime(article.date)}>{formatPublishedDateForDateTime(article.date)}</time>
                </div>
                <h2 className="post-title">
                  <a rel="bookmark" href={`/article/${article.stackbitUrlPath}`}>{article.title}</a>
                </h2>
              </header>
              <div className="post-excerpt">
                <p>{article.excerpt}</p>
                <p class="read-more"><a class="button button-secondary" href={`/article/${article.stackbitUrlPath}`}>Read more</a></p>
              </div>
            </div>
          </div>
        </article>
      </Link> 
      )}	
      </div>

        </div>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
